# Numpy Intro

## Reference:

1. https://www.w3schools.com/python/numpy_intro.asp  
2. https://numpy.org/  
3. http://www.learningaboutelectronics.com/Articles/How-to-create-an-array-of-random-integers-in-Python-with-numpy.php  


## Getting started

In [3]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

print(np.__version__)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1.18.5


## Using tuple to create array

In [4]:
arr = np.array((1,2,3,4,5,6,7))
print(arr)

[1 2 3 4 5 6 7]


## Dimensions

In [17]:
# 0 dimensional, with single value
arr = np.array(42)
print(arr)

# check number of dimensions
print("# of dimensions : ", arr.ndim) 

42
# of dimensions :  0


In [16]:
# 1 dimensional, with one array
arr = np.array([7,14,21,28,35,42])
print(arr)

# check number of dimensions
print("# of dimensions : ", arr.ndim) 

[ 7 14 21 28 35 42]
# of dimensions :  1


In [19]:
# 2 dimensional, an array that has 1D arrays as elements
arr = np.array([
        [1,2],
        [3,4]
    ])
print(arr)

# check number of dimensions
print("# of dimensions : ", arr.ndim) 

[[1 2]
 [3 4]]
# of dimensions :  2


In [18]:
# 3 dimensional, an array that has 2D arrays as its elements
arr = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,9]
    ]
])
print(arr)

# check number of dimensions
print("# of dimensions : ", arr.ndim) 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 9]]]
# of dimensions :  3


## Creating higher dimensional array using numpy

In [21]:
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
# check number of dimensions
print("# of dimensions : ", arr.ndim) 

[[[[[1 2 3 4]]]]]
# of dimensions :  5


In [46]:
arr = np.array([
    [[1,2,3,4],[5,6,7,8]],
    [[11,12,13,14],[15,16,17,18]]
], ndmin=5)
print(arr)
# check number of dimensions
print("# of dimensions : ", arr.ndim) 

[[[[[ 1  2  3  4]
    [ 5  6  7  8]]

   [[11 12 13 14]
    [15 16 17 18]]]]]
# of dimensions :  5


## Array indexing
Indexing is used to access the elemets in the array

In [51]:
print('accessing the 1st level')
print('-'*20)
print(arr[0])
print('-'*20)

print('accessing the 2nd level')
print('-'*20)
print(arr[0][0])
print('-'*20)

print('accessing the 3rd level')
print('-'*20)
print(arr[0][0][0])
print('-'*20)

print('accessing the 4th level')
print('-'*20)
print(arr[0][0][1][1])
print('-'*20)

print('accessing the 5th level')
print('-'*20)
print(arr[0][0][1][1][3])



accessing the 1st level
--------------------
[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[11 12 13 14]
   [15 16 17 18]]]]
--------------------
accessing the 2nd level
--------------------
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[11 12 13 14]
  [15 16 17 18]]]
--------------------
accessing the 3rd level
--------------------
[[1 2 3 4]
 [5 6 7 8]]
--------------------
accessing the 4th level
--------------------
[15 16 17 18]
--------------------
accessing the 5th level
--------------------
18


## Array can be accessed by passing an array of indices

arr\[l,m,n,o\] => returns the 4D array element, if its present

In [52]:
print('accessing the 1st level')
print('-'*20)
print(arr[0])
print('-'*20)

print('accessing the 2nd level')
print('-'*20)
print(arr[0,0])
print('-'*20)

print('accessing the 3rd level')
print('-'*20)
print(arr[0,0,0])
print('-'*20)

print('accessing the 4th level')
print('-'*20)
print(arr[0,0,1,1])
print('-'*20)

print('accessing the 5th level')
print('-'*20)
print(arr[0,0,1,1,3])

accessing the 1st level
--------------------
[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[11 12 13 14]
   [15 16 17 18]]]]
--------------------
accessing the 2nd level
--------------------
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[11 12 13 14]
  [15 16 17 18]]]
--------------------
accessing the 3rd level
--------------------
[[1 2 3 4]
 [5 6 7 8]]
--------------------
accessing the 4th level
--------------------
[15 16 17 18]
--------------------
accessing the 5th level
--------------------
18


## Negative indexing

In [61]:
print('accessing the 3rd level, last element')
print('-'*20)
print(arr[0,0,-1])
print('-'*20)

print('accessing the 4th level, last element')
print('-'*20)
print(arr[0,0,-1,-1])
print('-'*20)

print('accessing the 5th level, second last element of the first element at 4th level')
print('-'*20)
print(arr[0,0,-1,-2,-2])
print('-'*20)

accessing the 3rd level, last element
--------------------
[[11 12 13 14]
 [15 16 17 18]]
--------------------
accessing the 4th level, last element
--------------------
[15 16 17 18]
--------------------
accessing the 5th level, second last element of the first element at 4th level
--------------------
13
--------------------


## Array slicing

Slicing helps in taking elements from one index to another index

e.g.

arr\[start:end\]  
arr\[start:end:step\]  
arr\[start:end,start,:end\] etc.


In [80]:
# 1D array
arr = np.random.randint(1,100,10)
print(arr)
print("# of dims",arr.ndim)
print("-"*20)

print("printing elements from 2nd to 4th")
print(arr[1:4])

print("printing elements from 4nd to end")
print(arr[4:])

print("printing elements till 7th")
print(arr[:7])

[25  7 53 87 28 72 17 93 34 62]
# of dims 1
--------------------
printing elements from 2nd to 4th
[ 7 53 87]
printing elements from 4nd to end
[28 72 17 93 34 62]
printing elements till 7th
[25  7 53 87 28 72 17]


## Negative slicing

In [89]:
arr = np.random.randint(1,100,10)
print(arr)
print("# of dims",arr.ndim)
print("-"*20)


print("printing 3rd last elements till 2nd last elemet")
print(arr[-3:-1]) 
print("-"*20)

print("printing 6th last elements till the last elemet")
print(arr[-6:]) 

[73 72 21 10  8 46 24 27 53 77]
# of dims 1
--------------------
printing 3rd last elements till 2nd last elemet
[27 53]
--------------------
printing 6th last elements till the last elemet
[ 8 46 24 27 53 77]


## using step

In [92]:
arr = np.random.randint(1,100,10)
print(arr)
print("# of dims",arr.ndim)
print("-"*20)

print("elements at the 2nd index steps")
print(arr[::2])
print("-"*20)

print("elements at the 2nd index steps from 1st till 5th element")
print(arr[:5:2])
print("-"*20)

print("elements at even 2nd indices steps from 1st till 5th element")
print(arr[1:5:2])
print("-"*20)


[94 56 27 32 23 96 97 50 92 52]
# of dims 1
--------------------
elements at the 2nd index steps
[94 27 23 97 92]
--------------------
elements at the 2nd index steps from 1st till 5th element
[94 27 23]
--------------------
elements at even 2nd indices steps from 1st till 5th element
[56 32]
--------------------


In [152]:
# 2D array
arr = np.random.randint(1,100, size=(2,5))
print(arr)
print("# of dims",arr.ndim)
print("-"*20)

print("printing elements from index 0 ")
print(arr[0:])
print("# of dims",arr[0:].ndim)
print("-"*20)

print("printing the first element from 2D array ")
print(arr[0:1])
print("# of dims",arr[0:1].ndim)
print("-"*20)

print("printing the second elements from 2D array ")
print(arr[1:])
print("# of dims",arr[1:].ndim)
print("-"*20)

print("printing the second element of the second element from 2D array ")
print(arr[1:])
print("# of dims",arr[1:,1:2].ndim)
print("-"*20)

[[ 9 29 38 15 10]
 [80 25 64  4 45]]
# of dims 2
--------------------
printing elements from index 0 
[[ 9 29 38 15 10]
 [80 25 64  4 45]]
# of dims 2
--------------------
printing the first element from 2D array 
[[ 9 29 38 15 10]]
# of dims 2
--------------------
printing the second elements from 2D array 
[[80 25 64  4 45]]
# of dims 2
--------------------
printing the second element of the second element from 2D array 
[[80 25 64  4 45]]
# of dims 2
--------------------


In [154]:
# 2D array
arr = np.random.randint(1,100, size=(2,5))
print(arr)
print("# of dims",arr.ndim)
print("-"*20)


print("printing the 3rd and 4th elements from all rows of 2D array")
print(arr[0:,2:4])
print("# of dims",arr[0:,2:4].ndim)
print("-"*20)


print("printing the 3rd and 4th elements from the second row of 2D array")
print(arr[1:2,2:3])
print("# of dims",arr[1:2,2:3].ndim)
print("-"*20)


[[75 10 49 17  1]
 [51 82 68 99 88]]
# of dims 2
--------------------
printing the 3rd and 4th elements from all rows of 2D array
[[49 17]
 [68 99]]
# of dims 2
--------------------
printing the 3rd and 4th elements from the second row of 2D array
[[68]]
# of dims 2
--------------------


In [164]:
# 3D array
print("3 dimentional array, with 2 rows and 3 elements")
arr = np.random.randint(1,10, size=(3,2,3)) 
print(arr)
print("# of dims",arr.ndim)
print("-"*20)


print("3 dimentional array, with 5 rows and 7 elements")
arr = np.random.randint(1,100, size=(3,5,7)) 
print(arr)
print("# of dims",arr.ndim)
print("-"*20)

3 dimentional array, with 2 rows and 3 elements
[[[2 4 4]
  [4 6 5]]

 [[4 6 3]
  [6 8 3]]

 [[2 7 1]
  [6 7 6]]]
# of dims 3
--------------------
3 dimentional array, with 5 rows and 7 elements
[[[66 50 84 99 78 45 55]
  [21 10 19 50  2 67 21]
  [81 70 71 13 51 15 46]
  [25 60 64 48 84 49 91]
  [12 11 62 59 22  5 91]]

 [[52 15 81 17  2  5 88]
  [ 2 23  6 77 91 74 54]
  [21 36 32 96 92 17 25]
  [ 1 70 54 68 48 46 72]
  [55 62 27 27 85 77 62]]

 [[56 55  2 69 43 75  2]
  [59 94 49  7 93 65 49]
  [69 89 13 99 55 71 57]
  [52 28 72 26 70  7 32]
  [29 40  4 32 93  2 85]]]
# of dims 3
--------------------


In [165]:
print("the first item in the 3D array using simple index gives 1D array")
print(arr[0])
print("# of dims",arr[0].ndim)
print("-"*20)

print("the first item in the 3D array, using slice gives 3D array")
print(arr[0:1])
print("# of dims",arr[0:1].ndim)
print("-"*20)

the first item in the 3D array using simple index gives 1D array
[[66 50 84 99 78 45 55]
 [21 10 19 50  2 67 21]
 [81 70 71 13 51 15 46]
 [25 60 64 48 84 49 91]
 [12 11 62 59 22  5 91]]
# of dims 2
--------------------
the first item in the 3D array, using slice gives 3D array
[[[66 50 84 99 78 45 55]
  [21 10 19 50  2 67 21]
  [81 70 71 13 51 15 46]
  [25 60 64 48 84 49 91]
  [12 11 62 59 22  5 91]]]
# of dims 3
--------------------


In [169]:
print("the second element in 3D array")
print(arr[1:2])
print("# of dims",arr[0:1].ndim)
print("-"*20)

the second element in 3D array
[[[52 15 81 17  2  5 88]
  [ 2 23  6 77 91 74 54]
  [21 36 32 96 92 17 25]
  [ 1 70 54 68 48 46 72]
  [55 62 27 27 85 77 62]]]
# of dims 3
--------------------


In [172]:
print("the 3rd and 4th element from the second element in 3D array")
print(arr[1:2,2:4])
print("# of dims",arr[1:2,2:4].ndim)
print("-"*20)

the 3rd and 4th element from the second element in 3D array
[[[21 36 32 96 92 17 25]
  [ 1 70 54 68 48 46 72]]]
# of dims 3
--------------------


In [182]:
print("the 6th element from the 3rd and 4th element from the second element in 3D array")
print(arr[1:2,2:4,6:7])
print("# of dims",arr[1:2,2:4, 6:7].ndim)
print("-"*20)

print("the 6th element, from the 5th element from the second element in 3D array")

"""
1. 1:2 idexes the 2nd element of 3D array 
2. 4:5 indexes the 5th element of the array obtained as a result of step 1
3. 5:6 indexes the 6th element of the array obtained as a result of step 2
"""
print(arr[1:2,4:5,5:6]) 
print("# of dims",arr[1:2, 4:5, 5:6].ndim)
print("-"*20)

the 6th element from the 3rd and 4th element from the second element in 3D array
[[[25]
  [72]]]
# of dims 3
--------------------
the 6th element from the 5th element from the second element in 3D array
[[[77]]]
# of dims 3
--------------------


## Data types

Below is a list of all data types in NumPy and the characters used to represent them.

    i - integer
    b - boolean
    u - unsigned integer
    f - float
    c - complex float
    m - timedelta
    M - datetime
    O - object
    S - string
    U - unicode string
    V - fixed chunk of memory for other type ( void )


In [189]:
arr = np.array([1, 2, 3, 4])
print(arr)
print("datatype is : ",arr.dtype) 
print("-"*20)

arr = np.array(["apple", 'banana', 'mango', 'peach'])
print(arr)
print("datatype is : ",arr.dtype) 
print("-"*20)

print("with a defined datatype")
arr = np.array([1,2,3,4], dtype="S")
print(arr)
print("datatype is : ",arr.dtype) 
print("-"*20)

[1 2 3 4]
datatype is :  int64
--------------------
['apple' 'banana' 'mango' 'peach']
datatype is :  <U6
--------------------
with a defined datatype
[b'1' b'2' b'3' b'4']
datatype is :  |S1
--------------------


For i, u, f, S and U we can define size as well.

In [195]:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype) 
print("-"*20)

arr = np.array([1, 2, 3, 4], dtype='i8')
print(arr)
print(arr.dtype) 
print("-"*20)

[1 2 3 4]
int32
--------------------
[1 2 3 4]
int64
--------------------


## Converting datatype of existing array

In [200]:
arr = np.array([1.1, 2.1, 3.1])
print('Original array : ',arr)
print(arr.dtype) 
print('-'*20)

newarr = arr.astype('i')

print('New array',newarr)
print(newarr.dtype) 
print('-'*20)

Original array :  [1.1 2.1 3.1]
float64
--------------------
New array [1 2 3]
int32
--------------------


In [201]:
arr = np.array([1.1, 2.1, 3.1])
print('Original array : ',arr)
print(arr.dtype) 
print('-'*20)

newarr = arr.astype(int)

print('New array',newarr)
print(newarr.dtype) 
print('-'*20)

Original array :  [1.1 2.1 3.1]
float64
--------------------
New array [1 2 3]
int64
--------------------


In [203]:
arr = np.array([1.1, 2.1, 0.0])
print('Original array : ',arr)
print(arr.dtype) 
print('-'*20)

newarr = arr.astype(bool)

print('New array',newarr)
print(newarr.dtype) 
print('-'*20)

Original array :  [1.1 2.1 0. ]
float64
--------------------
New array [ True  True False]
bool
--------------------


In [204]:
arr = np.array([1.1, 2.1, 0.0])
print('Original array : ',arr)
print(arr.dtype) 
print('-'*20)

newarr = arr.astype(str)

print('New array',newarr)
print(newarr.dtype) 
print('-'*20)

Original array :  [1.1 2.1 0. ]
float64
--------------------
New array ['1.1' '2.1' '0.0']
<U32
--------------------


## Copy vs View

In [212]:
print("changing the element at index 0 of the original array has no effect on copy")
print("-"*20)

arr = np.array([1, 2, 3, 4, 5])
print("arr before changing the element :",arr)
x = arr.copy()
arr[0] = 42

print("arr :",arr)
print("x   :",x) 

changing the element at index 0 of the original array has no effect on copy
--------------------
arr before changing the element : [1 2 3 4 5]
arr : [42  2  3  4  5]
x   : [1 2 3 4 5]


In [213]:
print("changing the element at index 0 of the original array has effect on view")
print("-"*20)

arr = np.array([1, 2, 3, 4, 5])
print("arr before changing the element :",arr)
x = arr.view()
arr[0] = 42

print("arr :",arr)
print("x   :",x) 

changing the element at index 0 of the original array has effect on view
--------------------
arr before changing the element : [1 2 3 4 5]
arr : [42  2  3  4  5]
x   : [42  2  3  4  5]


### Every NumPy array has the attribute `base` that returns None if the array owns the data.



In [218]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print("base for copy : ",x.base)
print("base for view : ",y.base , ", => returns the original array") 

base for copy :  None
base for view :  [1 2 3 4 5] , => returns the original array


## Shape

In [222]:
print("3 dimentional array, with 5 rows and 7 elements")
arr = np.random.randint(1,100, size=(3,5,7)) 
print(arr)
print("# of dims",arr.ndim)
print("Shape of the array is : ", arr.shape)
print("Size of the array is : ", arr.size)
print("-"*20)

3 dimentional array, with 5 rows and 7 elements
[[[19 97 83 44 30  2 25]
  [12 69  4 95 47 48 30]
  [ 5 98 42 50 15  7 63]
  [89 68 54 75 98 99 48]
  [62 92 96 21 67 12 57]]

 [[52 71 58 29  7 33 22]
  [87 98 73  3  5 44 62]
  [14  4 32 61 43 57 83]
  [ 4 54 36 40 55 17 49]
  [35 85 85 41  9 47 76]]

 [[93 94 47 58 74 54 39]
  [85 73 31 20 41 10 72]
  [80 84 82 81 94  8 58]
  [34  3 64  8 22  7 59]
  [92 28 57 30 19 87 31]]]
# of dims 3
Shape of the array is :  (3, 5, 7)
Size of the array is :  105
--------------------


## Reshape

In [240]:
print("3 dimentional array, with 4 rows and 2 elements")
arr = np.random.randint(1,100, size=(3,4,2)) 
print(arr)
print("# of dims",arr.ndim)
print("Shape of the array is : ", arr.shape)
print("Size of the array is : ", arr.size)
print("-"*20)

print("Reshaping array to 4 dimentional array, with 2 rows of 3, 2D arrays")
"""
4th dimension has 2 3D arrays
3rd dimesion has 3 2D arrays
2nd dimension has 2 arrays with 2 elements each
1st dimention has 2 elements 
"""
newarr = arr.reshape(2,3,2,2) # should be equal to dimension
print(newarr)
print("# of dims in newarr",newarr.ndim)
print("Shape of the newarr is : ", newarr.shape) # why this is not changing?
print("Size of the newarr is : ", newarr.size)
print("-"*20)

3 dimentional array, with 4 rows and 2 elements
[[[50 21]
  [72 80]
  [20 79]
  [12 45]]

 [[46 93]
  [77  8]
  [50 85]
  [68 46]]

 [[99  8]
  [88 42]
  [49 23]
  [ 6 92]]]
# of dims 3
Shape of the array is :  (3, 4, 2)
Size of the array is :  24
--------------------
Reshaping array to 4 dimentional array, with 2 rows of 3, 2D arrays
[[[[50 21]
   [72 80]]

  [[20 79]
   [12 45]]

  [[46 93]
   [77  8]]]


 [[[50 85]
   [68 46]]

  [[99  8]
   [88 42]]

  [[49 23]
   [ 6 92]]]]
# of dims in newarr 4
Shape of the newarr is :  (2, 3, 2, 2)
Size of the newarr is :  24
--------------------


In [241]:
# can reshape only to same size array

# Unknown dimension
# Note: We can not pass -1 to more than one dimension.

"""
4th dimension has 6 3D arrays
3rd dimesion has 2 2D arrays
2nd dimension has 2 arrays with 1 elements each
1st dimention has 1 elements 
"""
newarr = arr.reshape(-1,2,2,1) # should be equal to dimension, 4 in this case as we want 4D array
print(newarr)
print("# of dims in newarr",newarr.ndim)
print("Shape of the newarr is : ", newarr.shape)
print("Size of the newarr is : ", newarr.size)
print("-"*20)


[[[[50]
   [21]]

  [[72]
   [80]]]


 [[[20]
   [79]]

  [[12]
   [45]]]


 [[[46]
   [93]]

  [[77]
   [ 8]]]


 [[[50]
   [85]]

  [[68]
   [46]]]


 [[[99]
   [ 8]]

  [[88]
   [42]]]


 [[[49]
   [23]]

  [[ 6]
   [92]]]]
# of dims in newarr 4
Shape of the newarr is :  (6, 2, 2, 1)
Size of the newarr is :  24
--------------------


## Flattening the arrays

In [242]:
flatarr = newarr.reshape(-1)
print(flatarr)
print("# of dims in flatarr",flatarr.ndim)
print("Shape of the flatarr is : ", flatarr.shape)
print("Size of the flatarr is : ", flatarr.size)
print("-"*20)


[50 21 72 80 20 79 12 45 46 93 77  8 50 85 68 46 99  8 88 42 49 23  6 92]
# of dims in flatarr 1
Shape of the flatarr is :  (24,)
Size of the flatarr is :  24
--------------------


**Note:** There are a lot of functions for changing the shapes of arrays in numpy `flatten`, `ravel` and also for rearranging the elements `rot90`, `flip`, `fliplr`, `flipud` etc. These fall under Intermediate to Advanced section of numpy.

In [248]:
print("flatten", newarr.flatten())
print("ravel  ", newarr.ravel())

flatten [50 21 72 80 20 79 12 45 46 93 77  8 50 85 68 46 99  8 88 42 49 23  6 92]
ravel   [50 21 72 80 20 79 12 45 46 93 77  8 50 85 68 46 99  8 88 42 49 23  6 92]


## Iterating

In [250]:
# 1D array
arr = np.random.randint(1,100,10)
for i in arr:
    print(i)

28
84
61
91
85
82
32
41
44
60


In [254]:
# 2D array
arr = np.random.randint(1,100, size=(3,5))
for k,v in enumerate(arr):
    print("row-"+str(k)+" : ",v)

row-0 :  [18 82  8 70 34]
row-1 :  [92 50 92 98 29]
row-2 :  [77  2 17 24 44]


In [259]:
# 3D array
arr = np.random.randint(1,100, size=(3,5,2))
for i,x in enumerate(arr):
    print("row-"+str(i)+" : \n",x)
    print("-"*20)
    for j,y in enumerate(x):
        print("row-"+str(i)+","+str(j)+" : ",y)
    print("="*20)

row-0 : 
 [[19 42]
 [73 21]
 [97 85]
 [ 5 35]
 [ 6 31]]
--------------------
row-0,0 :  [19 42]
row-0,1 :  [73 21]
row-0,2 :  [97 85]
row-0,3 :  [ 5 35]
row-0,4 :  [ 6 31]
row-1 : 
 [[20 99]
 [ 2 79]
 [91 81]
 [90 92]
 [22 44]]
--------------------
row-1,0 :  [20 99]
row-1,1 :  [ 2 79]
row-1,2 :  [91 81]
row-1,3 :  [90 92]
row-1,4 :  [22 44]
row-2 : 
 [[82 52]
 [53 18]
 [12 30]
 [86 97]
 [ 8 11]]
--------------------
row-2,0 :  [82 52]
row-2,1 :  [53 18]
row-2,2 :  [12 30]
row-2,3 :  [86 97]
row-2,4 :  [ 8 11]


In [275]:
# 4D array
arr = np.random.randint(1,100, size=(2,1,3,4))
for i,x in enumerate(arr):
    print("4D row-"+str(i)+" : \n",x)
    print("-"*20)
    for j,y in enumerate(x):
        print("3D row-"+str(i)+","+str(j)+" : \n",y)
        for k,z in enumerate(y):
            print("2D row-"+str(i)+","+str(j)+","+str(k)+" : ",z)
            for l,a in enumerate(z):
                print("1D row-"+str(i)+","+str(j)+","+str(k)+","+str(l)+" : ",a)
            print("="*20)

4D row-0 : 
 [[[69 57 18 87]
  [85 86 50 43]
  [42 11 14  8]]]
--------------------
3D row-0,0 : 
 [[69 57 18 87]
 [85 86 50 43]
 [42 11 14  8]]
2D row-0,0,0 :  [69 57 18 87]
1D row-0,0,0,0 :  69
1D row-0,0,0,1 :  57
1D row-0,0,0,2 :  18
1D row-0,0,0,3 :  87
2D row-0,0,1 :  [85 86 50 43]
1D row-0,0,1,0 :  85
1D row-0,0,1,1 :  86
1D row-0,0,1,2 :  50
1D row-0,0,1,3 :  43
2D row-0,0,2 :  [42 11 14  8]
1D row-0,0,2,0 :  42
1D row-0,0,2,1 :  11
1D row-0,0,2,2 :  14
1D row-0,0,2,3 :  8
4D row-1 : 
 [[[64 85  2 23]
  [14 68 65 39]
  [ 2  7  4 33]]]
--------------------
3D row-1,0 : 
 [[64 85  2 23]
 [14 68 65 39]
 [ 2  7  4 33]]
2D row-1,0,0 :  [64 85  2 23]
1D row-1,0,0,0 :  64
1D row-1,0,0,1 :  85
1D row-1,0,0,2 :  2
1D row-1,0,0,3 :  23
2D row-1,0,1 :  [14 68 65 39]
1D row-1,0,1,0 :  14
1D row-1,0,1,1 :  68
1D row-1,0,1,2 :  65
1D row-1,0,1,3 :  39
2D row-1,0,2 :  [ 2  7  4 33]
1D row-1,0,2,0 :  2
1D row-1,0,2,1 :  7
1D row-1,0,2,2 :  4
1D row-1,0,2,3 :  33


## Iterating Arrays Using `nditer()`

The function nditer() is a helping function that can be used from very basic to very advanced iterations. 

In [278]:
# 3D array
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# prints each element in the nd array
for x in np.nditer(arr):
  print(x) 

1
2
3
4
5
6
7
8


## Iterating Array With Different Data Types

We can use `op_dtypes` argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in `nditer()` we pass `flags=['buffered']`.

In [284]:
# 3D array
arr = np.random.randint(1,100, size=(2,2,2))

for i in np.nditer(arr, op_dtypes=['S'], flags=['buffered']):
    print(i)

b'95'
b'81'
b'50'
b'98'
b'97'
b'27'
b'34'
b'70'


## nditer step size



In [303]:
# 3D array
arr = np.random.randint(1,100, size=(5,3,8))

print(arr)
print('-'*20)
print(arr[1:5:2, ::2,3::4])

"""
1. identify the rows from 3D array, 1:5:2 => every other row starting from 2nd element, (index 1 and 3)
2. get row at index 0 and 2 from array at index 1 and 3 from prev step
3. get every 4th element, starting form index 3 from prev step result
"""
for x in np.nditer(arr[1:5:2, ::2,3::4]):
  print(x) 


[[[19 99  4 24 42 89 27 34]
  [99 99 29 66 58 94 85 26]
  [52 36  9 58 16 90 87 13]]

 [[36  8 11 85 25  6 95 96]
  [58 92 36 81 87 12 39 43]
  [32 57 25 23 99 65 90 33]]

 [[69  4 72  6 80 34 17 79]
  [76 24 15 52 51 81 39 31]
  [69 76  6 16 59 16 54 32]]

 [[77 51 97 65 85 79 67 67]
  [93 66 82 32 74 30 68 20]
  [43 75 22 89 78 28 10 24]]

 [[39 91 77  7 11 28 26 16]
  [ 7 96  8 89 84 20 76 98]
  [13 81 51 45 82 37 20 23]]]
--------------------
[[[85 96]
  [23 33]]

 [[65 67]
  [89 24]]]
85
96
23
33
65
67
89
24


## Enumerated Iteration Using `ndenumerate()`

In [304]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr):
  print(idx, x) 

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [305]:
arr  = np.random.randint(1,100,size=(4,5,2))
for idx,x in np.ndenumerate(arr):
    print(idx,x)

(0, 0, 0) 92
(0, 0, 1) 56
(0, 1, 0) 88
(0, 1, 1) 1
(0, 2, 0) 42
(0, 2, 1) 71
(0, 3, 0) 79
(0, 3, 1) 18
(0, 4, 0) 84
(0, 4, 1) 31
(1, 0, 0) 71
(1, 0, 1) 20
(1, 1, 0) 13
(1, 1, 1) 43
(1, 2, 0) 21
(1, 2, 1) 13
(1, 3, 0) 51
(1, 3, 1) 17
(1, 4, 0) 15
(1, 4, 1) 11
(2, 0, 0) 4
(2, 0, 1) 98
(2, 1, 0) 78
(2, 1, 1) 57
(2, 2, 0) 1
(2, 2, 1) 13
(2, 3, 0) 60
(2, 3, 1) 95
(2, 4, 0) 54
(2, 4, 1) 67
(3, 0, 0) 95
(3, 0, 1) 44
(3, 1, 0) 69
(3, 1, 1) 88
(3, 2, 0) 58
(3, 2, 1) 30
(3, 3, 0) 97
(3, 3, 1) 13
(3, 4, 0) 95
(3, 4, 1) 79
