# Numpy Intro

## Reference:

1. https://www.w3schools.com/python/numpy_intro.asp  
2. https://numpy.org/  
3. http://www.learningaboutelectronics.com/Articles/How-to-create-an-array-of-random-integers-in-Python-with-numpy.php  


## Getting started

In [3]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

print(np.__version__)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1.18.5


## Using tuple to create array

In [4]:
arr = np.array((1,2,3,4,5,6,7))
print(arr)

[1 2 3 4 5 6 7]


## Dimensions

In [17]:
# 0 dimensional, with single value
arr = np.array(42)
print(arr)

# check number of dimensions
print("# of dimensions : ", arr.ndim) 

42
# of dimensions :  0


In [16]:
# 1 dimensional, with one array
arr = np.array([7,14,21,28,35,42])
print(arr)

# check number of dimensions
print("# of dimensions : ", arr.ndim) 

[ 7 14 21 28 35 42]
# of dimensions :  1


In [19]:
# 2 dimensional, an array that has 1D arrays as elements
arr = np.array([
        [1,2],
        [3,4]
    ])
print(arr)

# check number of dimensions
print("# of dimensions : ", arr.ndim) 

[[1 2]
 [3 4]]
# of dimensions :  2


In [18]:
# 3 dimensional, an array that has 2D arrays as its elements
arr = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,9]
    ]
])
print(arr)

# check number of dimensions
print("# of dimensions : ", arr.ndim) 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 9]]]
# of dimensions :  3


## Creating higher dimensional array using numpy

In [21]:
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
# check number of dimensions
print("# of dimensions : ", arr.ndim) 

[[[[[1 2 3 4]]]]]
# of dimensions :  5


In [46]:
arr = np.array([
    [[1,2,3,4],[5,6,7,8]],
    [[11,12,13,14],[15,16,17,18]]
], ndmin=5)
print(arr)
# check number of dimensions
print("# of dimensions : ", arr.ndim) 

[[[[[ 1  2  3  4]
    [ 5  6  7  8]]

   [[11 12 13 14]
    [15 16 17 18]]]]]
# of dimensions :  5


## Array indexing
Indexing is used to access the elemets in the array

In [51]:
print('accessing the 1st level')
print('-'*20)
print(arr[0])
print('-'*20)

print('accessing the 2nd level')
print('-'*20)
print(arr[0][0])
print('-'*20)

print('accessing the 3rd level')
print('-'*20)
print(arr[0][0][0])
print('-'*20)

print('accessing the 4th level')
print('-'*20)
print(arr[0][0][1][1])
print('-'*20)

print('accessing the 5th level')
print('-'*20)
print(arr[0][0][1][1][3])



accessing the 1st level
--------------------
[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[11 12 13 14]
   [15 16 17 18]]]]
--------------------
accessing the 2nd level
--------------------
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[11 12 13 14]
  [15 16 17 18]]]
--------------------
accessing the 3rd level
--------------------
[[1 2 3 4]
 [5 6 7 8]]
--------------------
accessing the 4th level
--------------------
[15 16 17 18]
--------------------
accessing the 5th level
--------------------
18


## Array can be accessed by passing an array of indices

arr\[l,m,n,o\] => returns the 4D array element, if its present

In [52]:
print('accessing the 1st level')
print('-'*20)
print(arr[0])
print('-'*20)

print('accessing the 2nd level')
print('-'*20)
print(arr[0,0])
print('-'*20)

print('accessing the 3rd level')
print('-'*20)
print(arr[0,0,0])
print('-'*20)

print('accessing the 4th level')
print('-'*20)
print(arr[0,0,1,1])
print('-'*20)

print('accessing the 5th level')
print('-'*20)
print(arr[0,0,1,1,3])

accessing the 1st level
--------------------
[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[11 12 13 14]
   [15 16 17 18]]]]
--------------------
accessing the 2nd level
--------------------
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[11 12 13 14]
  [15 16 17 18]]]
--------------------
accessing the 3rd level
--------------------
[[1 2 3 4]
 [5 6 7 8]]
--------------------
accessing the 4th level
--------------------
[15 16 17 18]
--------------------
accessing the 5th level
--------------------
18


## Negative indexing

In [61]:
print('accessing the 3rd level, last element')
print('-'*20)
print(arr[0,0,-1])
print('-'*20)

print('accessing the 4th level, last element')
print('-'*20)
print(arr[0,0,-1,-1])
print('-'*20)

print('accessing the 5th level, second last element of the first element at 4th level')
print('-'*20)
print(arr[0,0,-1,-2,-2])
print('-'*20)

accessing the 3rd level, last element
--------------------
[[11 12 13 14]
 [15 16 17 18]]
--------------------
accessing the 4th level, last element
--------------------
[15 16 17 18]
--------------------
accessing the 5th level, second last element of the first element at 4th level
--------------------
13
--------------------


## Array slicing

Slicing helps in taking elements from one index to another index

e.g.

arr\[start:end\]  
arr\[start:end:step\]  
arr\[start:end,start,:end\] etc.


In [80]:
# 1D array
arr = np.random.randint(1,100,10)
print(arr)
print("# of dims",arr.ndim)
print("-"*20)

print("printing elements from 2nd to 4th")
print(arr[1:4])

print("printing elements from 4nd to end")
print(arr[4:])

print("printing elements till 7th")
print(arr[:7])

[25  7 53 87 28 72 17 93 34 62]
# of dims 1
--------------------
printing elements from 2nd to 4th
[ 7 53 87]
printing elements from 4nd to end
[28 72 17 93 34 62]
printing elements till 7th
[25  7 53 87 28 72 17]


## Negative slicing

In [89]:
arr = np.random.randint(1,100,10)
print(arr)
print("# of dims",arr.ndim)
print("-"*20)


print("printing 3rd last elements till 2nd last elemet")
print(arr[-3:-1]) 
print("-"*20)

print("printing 6th last elements till the last elemet")
print(arr[-6:]) 

[73 72 21 10  8 46 24 27 53 77]
# of dims 1
--------------------
printing 3rd last elements till 2nd last elemet
[27 53]
--------------------
printing 6th last elements till the last elemet
[ 8 46 24 27 53 77]


## using step

In [92]:
arr = np.random.randint(1,100,10)
print(arr)
print("# of dims",arr.ndim)
print("-"*20)

print("elements at the 2nd index steps")
print(arr[::2])
print("-"*20)

print("elements at the 2nd index steps from 1st till 5th element")
print(arr[:5:2])
print("-"*20)

print("elements at even 2nd indices steps from 1st till 5th element")
print(arr[1:5:2])
print("-"*20)


[94 56 27 32 23 96 97 50 92 52]
# of dims 1
--------------------
elements at the 2nd index steps
[94 27 23 97 92]
--------------------
elements at the 2nd index steps from 1st till 5th element
[94 27 23]
--------------------
elements at even 2nd indices steps from 1st till 5th element
[56 32]
--------------------


In [152]:
# 2D array
arr = np.random.randint(1,100, size=(2,5))
print(arr)
print("# of dims",arr.ndim)
print("-"*20)

print("printing elements from index 0 ")
print(arr[0:])
print("# of dims",arr[0:].ndim)
print("-"*20)

print("printing the first element from 2D array ")
print(arr[0:1])
print("# of dims",arr[0:1].ndim)
print("-"*20)

print("printing the second elements from 2D array ")
print(arr[1:])
print("# of dims",arr[1:].ndim)
print("-"*20)

print("printing the second element of the second element from 2D array ")
print(arr[1:])
print("# of dims",arr[1:,1:2].ndim)
print("-"*20)

[[ 9 29 38 15 10]
 [80 25 64  4 45]]
# of dims 2
--------------------
printing elements from index 0 
[[ 9 29 38 15 10]
 [80 25 64  4 45]]
# of dims 2
--------------------
printing the first element from 2D array 
[[ 9 29 38 15 10]]
# of dims 2
--------------------
printing the second elements from 2D array 
[[80 25 64  4 45]]
# of dims 2
--------------------
printing the second element of the second element from 2D array 
[[80 25 64  4 45]]
# of dims 2
--------------------


In [154]:
# 2D array
arr = np.random.randint(1,100, size=(2,5))
print(arr)
print("# of dims",arr.ndim)
print("-"*20)


print("printing the 3rd and 4th elements from all rows of 2D array")
print(arr[0:,2:4])
print("# of dims",arr[0:,2:4].ndim)
print("-"*20)


print("printing the 3rd and 4th elements from the second row of 2D array")
print(arr[1:2,2:3])
print("# of dims",arr[1:2,2:3].ndim)
print("-"*20)


[[75 10 49 17  1]
 [51 82 68 99 88]]
# of dims 2
--------------------
printing the 3rd and 4th elements from all rows of 2D array
[[49 17]
 [68 99]]
# of dims 2
--------------------
printing the 3rd and 4th elements from the second row of 2D array
[[68]]
# of dims 2
--------------------


In [164]:
# 3D array
print("3 dimentional array, with 2 rows and 3 elements")
arr = np.random.randint(1,10, size=(3,2,3)) 
print(arr)
print("# of dims",arr.ndim)
print("-"*20)


print("3 dimentional array, with 5 rows and 7 elements")
arr = np.random.randint(1,100, size=(3,5,7)) 
print(arr)
print("# of dims",arr.ndim)
print("-"*20)

3 dimentional array, with 2 rows and 3 elements
[[[2 4 4]
  [4 6 5]]

 [[4 6 3]
  [6 8 3]]

 [[2 7 1]
  [6 7 6]]]
# of dims 3
--------------------
3 dimentional array, with 5 rows and 7 elements
[[[66 50 84 99 78 45 55]
  [21 10 19 50  2 67 21]
  [81 70 71 13 51 15 46]
  [25 60 64 48 84 49 91]
  [12 11 62 59 22  5 91]]

 [[52 15 81 17  2  5 88]
  [ 2 23  6 77 91 74 54]
  [21 36 32 96 92 17 25]
  [ 1 70 54 68 48 46 72]
  [55 62 27 27 85 77 62]]

 [[56 55  2 69 43 75  2]
  [59 94 49  7 93 65 49]
  [69 89 13 99 55 71 57]
  [52 28 72 26 70  7 32]
  [29 40  4 32 93  2 85]]]
# of dims 3
--------------------


In [165]:
print("the first item in the 3D array using simple index gives 1D array")
print(arr[0])
print("# of dims",arr[0].ndim)
print("-"*20)

print("the first item in the 3D array, using slice gives 3D array")
print(arr[0:1])
print("# of dims",arr[0:1].ndim)
print("-"*20)

the first item in the 3D array using simple index gives 1D array
[[66 50 84 99 78 45 55]
 [21 10 19 50  2 67 21]
 [81 70 71 13 51 15 46]
 [25 60 64 48 84 49 91]
 [12 11 62 59 22  5 91]]
# of dims 2
--------------------
the first item in the 3D array, using slice gives 3D array
[[[66 50 84 99 78 45 55]
  [21 10 19 50  2 67 21]
  [81 70 71 13 51 15 46]
  [25 60 64 48 84 49 91]
  [12 11 62 59 22  5 91]]]
# of dims 3
--------------------


In [169]:
print("the second element in 3D array")
print(arr[1:2])
print("# of dims",arr[0:1].ndim)
print("-"*20)

the second element in 3D array
[[[52 15 81 17  2  5 88]
  [ 2 23  6 77 91 74 54]
  [21 36 32 96 92 17 25]
  [ 1 70 54 68 48 46 72]
  [55 62 27 27 85 77 62]]]
# of dims 3
--------------------


In [172]:
print("the 3rd and 4th element from the second element in 3D array")
print(arr[1:2,2:4])
print("# of dims",arr[1:2,2:4].ndim)
print("-"*20)

the 3rd and 4th element from the second element in 3D array
[[[21 36 32 96 92 17 25]
  [ 1 70 54 68 48 46 72]]]
# of dims 3
--------------------


In [182]:
print("the 6th element from the 3rd and 4th element from the second element in 3D array")
print(arr[1:2,2:4,6:7])
print("# of dims",arr[1:2,2:4, 6:7].ndim)
print("-"*20)

print("the 6th element, from the 5th element from the second element in 3D array")

"""
1. 1:2 idexes the 2nd element of 3D array 
2. 4:5 indexes the 5th element of the array obtained as a result of step 1
3. 5:6 indexes the 6th element of the array obtained as a result of step 2
"""
print(arr[1:2,4:5,5:6]) 
print("# of dims",arr[1:2, 4:5, 5:6].ndim)
print("-"*20)

the 6th element from the 3rd and 4th element from the second element in 3D array
[[[25]
  [72]]]
# of dims 3
--------------------
the 6th element from the 5th element from the second element in 3D array
[[[77]]]
# of dims 3
--------------------


## Data types

Below is a list of all data types in NumPy and the characters used to represent them.

    i - integer
    b - boolean
    u - unsigned integer
    f - float
    c - complex float
    m - timedelta
    M - datetime
    O - object
    S - string
    U - unicode string
    V - fixed chunk of memory for other type ( void )


In [189]:
arr = np.array([1, 2, 3, 4])
print(arr)
print("datatype is : ",arr.dtype) 
print("-"*20)

arr = np.array(["apple", 'banana', 'mango', 'peach'])
print(arr)
print("datatype is : ",arr.dtype) 
print("-"*20)

print("with a defined datatype")
arr = np.array([1,2,3,4], dtype="S")
print(arr)
print("datatype is : ",arr.dtype) 
print("-"*20)

[1 2 3 4]
datatype is :  int64
--------------------
['apple' 'banana' 'mango' 'peach']
datatype is :  <U6
--------------------
with a defined datatype
[b'1' b'2' b'3' b'4']
datatype is :  |S1
--------------------


For i, u, f, S and U we can define size as well.

In [195]:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype) 
print("-"*20)

arr = np.array([1, 2, 3, 4], dtype='i8')
print(arr)
print(arr.dtype) 
print("-"*20)

[1 2 3 4]
int32
--------------------
[1 2 3 4]
int64
--------------------


## Converting datatype of existing array

In [200]:
arr = np.array([1.1, 2.1, 3.1])
print('Original array : ',arr)
print(arr.dtype) 
print('-'*20)

newarr = arr.astype('i')

print('New array',newarr)
print(newarr.dtype) 
print('-'*20)

Original array :  [1.1 2.1 3.1]
float64
--------------------
New array [1 2 3]
int32
--------------------


In [201]:
arr = np.array([1.1, 2.1, 3.1])
print('Original array : ',arr)
print(arr.dtype) 
print('-'*20)

newarr = arr.astype(int)

print('New array',newarr)
print(newarr.dtype) 
print('-'*20)

Original array :  [1.1 2.1 3.1]
float64
--------------------
New array [1 2 3]
int64
--------------------


In [203]:
arr = np.array([1.1, 2.1, 0.0])
print('Original array : ',arr)
print(arr.dtype) 
print('-'*20)

newarr = arr.astype(bool)

print('New array',newarr)
print(newarr.dtype) 
print('-'*20)

Original array :  [1.1 2.1 0. ]
float64
--------------------
New array [ True  True False]
bool
--------------------


In [204]:
arr = np.array([1.1, 2.1, 0.0])
print('Original array : ',arr)
print(arr.dtype) 
print('-'*20)

newarr = arr.astype(str)

print('New array',newarr)
print(newarr.dtype) 
print('-'*20)

Original array :  [1.1 2.1 0. ]
float64
--------------------
New array ['1.1' '2.1' '0.0']
<U32
--------------------
