# Numpy Intro

## Reference:

1. https://www.w3schools.com/python/numpy_intro.asp  
2. https://numpy.org/  
3. http://www.learningaboutelectronics.com/Articles/How-to-create-an-array-of-random-integers-in-Python-with-numpy.php  


## Getting started

In [3]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

print(np.__version__)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1.18.5


## Using tuple to create array

In [4]:
arr = np.array((1,2,3,4,5,6,7))
print(arr)

[1 2 3 4 5 6 7]


## Dimensions

In [17]:
# 0 dimensional, with single value
arr = np.array(42)
print(arr)

# check number of dimensions
print("# of dimensions : ", arr.ndim) 

42
# of dimensions :  0


In [16]:
# 1 dimensional, with one array
arr = np.array([7,14,21,28,35,42])
print(arr)

# check number of dimensions
print("# of dimensions : ", arr.ndim) 

[ 7 14 21 28 35 42]
# of dimensions :  1


In [19]:
# 2 dimensional, an array that has 1D arrays as elements
arr = np.array([
        [1,2],
        [3,4]
    ])
print(arr)

# check number of dimensions
print("# of dimensions : ", arr.ndim) 

[[1 2]
 [3 4]]
# of dimensions :  2


In [18]:
# 3 dimensional, an array that has 2D arrays as its elements
arr = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,9]
    ]
])
print(arr)

# check number of dimensions
print("# of dimensions : ", arr.ndim) 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 9]]]
# of dimensions :  3


## Creating higher dimensional array using numpy

In [21]:
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
# check number of dimensions
print("# of dimensions : ", arr.ndim) 

[[[[[1 2 3 4]]]]]
# of dimensions :  5


In [46]:
arr = np.array([
    [[1,2,3,4],[5,6,7,8]],
    [[11,12,13,14],[15,16,17,18]]
], ndmin=5)
print(arr)
# check number of dimensions
print("# of dimensions : ", arr.ndim) 

[[[[[ 1  2  3  4]
    [ 5  6  7  8]]

   [[11 12 13 14]
    [15 16 17 18]]]]]
# of dimensions :  5


## Array indexing
Indexing is used to access the elemets in the array

In [51]:
print('accessing the 1st level')
print('-'*20)
print(arr[0])
print('-'*20)

print('accessing the 2nd level')
print('-'*20)
print(arr[0][0])
print('-'*20)

print('accessing the 3rd level')
print('-'*20)
print(arr[0][0][0])
print('-'*20)

print('accessing the 4th level')
print('-'*20)
print(arr[0][0][1][1])
print('-'*20)

print('accessing the 5th level')
print('-'*20)
print(arr[0][0][1][1][3])



accessing the 1st level
--------------------
[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[11 12 13 14]
   [15 16 17 18]]]]
--------------------
accessing the 2nd level
--------------------
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[11 12 13 14]
  [15 16 17 18]]]
--------------------
accessing the 3rd level
--------------------
[[1 2 3 4]
 [5 6 7 8]]
--------------------
accessing the 4th level
--------------------
[15 16 17 18]
--------------------
accessing the 5th level
--------------------
18


## Array can be accessed by passing an array of indices

arr\[l,m,n,o\] => returns the 4D array element, if its present

In [52]:
print('accessing the 1st level')
print('-'*20)
print(arr[0])
print('-'*20)

print('accessing the 2nd level')
print('-'*20)
print(arr[0,0])
print('-'*20)

print('accessing the 3rd level')
print('-'*20)
print(arr[0,0,0])
print('-'*20)

print('accessing the 4th level')
print('-'*20)
print(arr[0,0,1,1])
print('-'*20)

print('accessing the 5th level')
print('-'*20)
print(arr[0,0,1,1,3])

accessing the 1st level
--------------------
[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[11 12 13 14]
   [15 16 17 18]]]]
--------------------
accessing the 2nd level
--------------------
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[11 12 13 14]
  [15 16 17 18]]]
--------------------
accessing the 3rd level
--------------------
[[1 2 3 4]
 [5 6 7 8]]
--------------------
accessing the 4th level
--------------------
[15 16 17 18]
--------------------
accessing the 5th level
--------------------
18


## Negative indexing

In [61]:
print('accessing the 3rd level, last element')
print('-'*20)
print(arr[0,0,-1])
print('-'*20)

print('accessing the 4th level, last element')
print('-'*20)
print(arr[0,0,-1,-1])
print('-'*20)

print('accessing the 5th level, second last element of the first element at 4th level')
print('-'*20)
print(arr[0,0,-1,-2,-2])
print('-'*20)

accessing the 3rd level, last element
--------------------
[[11 12 13 14]
 [15 16 17 18]]
--------------------
accessing the 4th level, last element
--------------------
[15 16 17 18]
--------------------
accessing the 5th level, second last element of the first element at 4th level
--------------------
13
--------------------


## Array slicing

Slicing helps in taking elements from one index to another index

e.g.

arr\[start:end\]  
arr\[start:end:step\]  
arr\[start:end,start,:end\] etc.


In [80]:
# 1D array
arr = np.random.randint(1,100,10)
print(arr)
print("# of dims",arr.ndim)
print("-"*20)

print("printing elements from 2nd to 4th")
print(arr[1:4])

print("printing elements from 4nd to end")
print(arr[4:])

print("printing elements till 7th")
print(arr[:7])

[25  7 53 87 28 72 17 93 34 62]
# of dims 1
--------------------
printing elements from 2nd to 4th
[ 7 53 87]
printing elements from 4nd to end
[28 72 17 93 34 62]
printing elements till 7th
[25  7 53 87 28 72 17]


## Negative slicing

In [89]:
arr = np.random.randint(1,100,10)
print(arr)
print("# of dims",arr.ndim)
print("-"*20)


print("printing 3rd last elements till 2nd last elemet")
print(arr[-3:-1]) 
print("-"*20)

print("printing 6th last elements till the last elemet")
print(arr[-6:]) 

[73 72 21 10  8 46 24 27 53 77]
# of dims 1
--------------------
printing 3rd last elements till 2nd last elemet
[27 53]
--------------------
printing 6th last elements till the last elemet
[ 8 46 24 27 53 77]


## using step

In [92]:
arr = np.random.randint(1,100,10)
print(arr)
print("# of dims",arr.ndim)
print("-"*20)

print("elements at the 2nd index steps")
print(arr[::2])
print("-"*20)

print("elements at the 2nd index steps from 1st till 5th element")
print(arr[:5:2])
print("-"*20)

print("elements at even 2nd indices steps from 1st till 5th element")
print(arr[1:5:2])
print("-"*20)


[94 56 27 32 23 96 97 50 92 52]
# of dims 1
--------------------
elements at the 2nd index steps
[94 27 23 97 92]
--------------------
elements at the 2nd index steps from 1st till 5th element
[94 27 23]
--------------------
elements at even 2nd indices steps from 1st till 5th element
[56 32]
--------------------


In [152]:
# 2D array
arr = np.random.randint(1,100, size=(2,5))
print(arr)
print("# of dims",arr.ndim)
print("-"*20)

print("printing elements from index 0 ")
print(arr[0:])
print("# of dims",arr[0:].ndim)
print("-"*20)

print("printing the first element from 2D array ")
print(arr[0:1])
print("# of dims",arr[0:1].ndim)
print("-"*20)

print("printing the second elements from 2D array ")
print(arr[1:])
print("# of dims",arr[1:].ndim)
print("-"*20)

print("printing the second element of the second element from 2D array ")
print(arr[1:])
print("# of dims",arr[1:,1:2].ndim)
print("-"*20)

[[ 9 29 38 15 10]
 [80 25 64  4 45]]
# of dims 2
--------------------
printing elements from index 0 
[[ 9 29 38 15 10]
 [80 25 64  4 45]]
# of dims 2
--------------------
printing the first element from 2D array 
[[ 9 29 38 15 10]]
# of dims 2
--------------------
printing the second elements from 2D array 
[[80 25 64  4 45]]
# of dims 2
--------------------
printing the second element of the second element from 2D array 
[[80 25 64  4 45]]
# of dims 2
--------------------


In [154]:
# 2D array
arr = np.random.randint(1,100, size=(2,5))
print(arr)
print("# of dims",arr.ndim)
print("-"*20)


print("printing the 3rd and 4th elements from all rows of 2D array")
print(arr[0:,2:4])
print("# of dims",arr[0:,2:4].ndim)
print("-"*20)


print("printing the 3rd and 4th elements from the second row of 2D array")
print(arr[1:2,2:3])
print("# of dims",arr[1:2,2:3].ndim)
print("-"*20)


[[75 10 49 17  1]
 [51 82 68 99 88]]
# of dims 2
--------------------
printing the 3rd and 4th elements from all rows of 2D array
[[49 17]
 [68 99]]
# of dims 2
--------------------
printing the 3rd and 4th elements from the second row of 2D array
[[68]]
# of dims 2
--------------------


In [164]:
# 3D array
print("3 dimentional array, with 2 rows and 3 elements")
arr = np.random.randint(1,10, size=(3,2,3)) 
print(arr)
print("# of dims",arr.ndim)
print("-"*20)


print("3 dimentional array, with 5 rows and 7 elements")
arr = np.random.randint(1,100, size=(3,5,7)) 
print(arr)
print("# of dims",arr.ndim)
print("-"*20)

3 dimentional array, with 2 rows and 3 elements
[[[2 4 4]
  [4 6 5]]

 [[4 6 3]
  [6 8 3]]

 [[2 7 1]
  [6 7 6]]]
# of dims 3
--------------------
3 dimentional array, with 5 rows and 7 elements
[[[66 50 84 99 78 45 55]
  [21 10 19 50  2 67 21]
  [81 70 71 13 51 15 46]
  [25 60 64 48 84 49 91]
  [12 11 62 59 22  5 91]]

 [[52 15 81 17  2  5 88]
  [ 2 23  6 77 91 74 54]
  [21 36 32 96 92 17 25]
  [ 1 70 54 68 48 46 72]
  [55 62 27 27 85 77 62]]

 [[56 55  2 69 43 75  2]
  [59 94 49  7 93 65 49]
  [69 89 13 99 55 71 57]
  [52 28 72 26 70  7 32]
  [29 40  4 32 93  2 85]]]
# of dims 3
--------------------


In [165]:
print("the first item in the 3D array using simple index gives 1D array")
print(arr[0])
print("# of dims",arr[0].ndim)
print("-"*20)

print("the first item in the 3D array, using slice gives 3D array")
print(arr[0:1])
print("# of dims",arr[0:1].ndim)
print("-"*20)

the first item in the 3D array using simple index gives 1D array
[[66 50 84 99 78 45 55]
 [21 10 19 50  2 67 21]
 [81 70 71 13 51 15 46]
 [25 60 64 48 84 49 91]
 [12 11 62 59 22  5 91]]
# of dims 2
--------------------
the first item in the 3D array, using slice gives 3D array
[[[66 50 84 99 78 45 55]
  [21 10 19 50  2 67 21]
  [81 70 71 13 51 15 46]
  [25 60 64 48 84 49 91]
  [12 11 62 59 22  5 91]]]
# of dims 3
--------------------


In [169]:
print("the second element in 3D array")
print(arr[1:2])
print("# of dims",arr[0:1].ndim)
print("-"*20)

the second element in 3D array
[[[52 15 81 17  2  5 88]
  [ 2 23  6 77 91 74 54]
  [21 36 32 96 92 17 25]
  [ 1 70 54 68 48 46 72]
  [55 62 27 27 85 77 62]]]
# of dims 3
--------------------


In [172]:
print("the 3rd and 4th element from the second element in 3D array")
print(arr[1:2,2:4])
print("# of dims",arr[1:2,2:4].ndim)
print("-"*20)

the 3rd and 4th element from the second element in 3D array
[[[21 36 32 96 92 17 25]
  [ 1 70 54 68 48 46 72]]]
# of dims 3
--------------------


In [182]:
print("the 6th element from the 3rd and 4th element from the second element in 3D array")
print(arr[1:2,2:4,6:7])
print("# of dims",arr[1:2,2:4, 6:7].ndim)
print("-"*20)

print("the 6th element, from the 5th element from the second element in 3D array")

"""
1. 1:2 idexes the 2nd element of 3D array 
2. 4:5 indexes the 5th element of the array obtained as a result of step 1
3. 5:6 indexes the 6th element of the array obtained as a result of step 2
"""
print(arr[1:2,4:5,5:6]) 
print("# of dims",arr[1:2, 4:5, 5:6].ndim)
print("-"*20)

the 6th element from the 3rd and 4th element from the second element in 3D array
[[[25]
  [72]]]
# of dims 3
--------------------
the 6th element from the 5th element from the second element in 3D array
[[[77]]]
# of dims 3
--------------------


## Data types

Below is a list of all data types in NumPy and the characters used to represent them.

    i - integer
    b - boolean
    u - unsigned integer
    f - float
    c - complex float
    m - timedelta
    M - datetime
    O - object
    S - string
    U - unicode string
    V - fixed chunk of memory for other type ( void )


In [189]:
arr = np.array([1, 2, 3, 4])
print(arr)
print("datatype is : ",arr.dtype) 
print("-"*20)

arr = np.array(["apple", 'banana', 'mango', 'peach'])
print(arr)
print("datatype is : ",arr.dtype) 
print("-"*20)

print("with a defined datatype")
arr = np.array([1,2,3,4], dtype="S")
print(arr)
print("datatype is : ",arr.dtype) 
print("-"*20)

[1 2 3 4]
datatype is :  int64
--------------------
['apple' 'banana' 'mango' 'peach']
datatype is :  <U6
--------------------
with a defined datatype
[b'1' b'2' b'3' b'4']
datatype is :  |S1
--------------------


For i, u, f, S and U we can define size as well.

In [195]:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype) 
print("-"*20)

arr = np.array([1, 2, 3, 4], dtype='i8')
print(arr)
print(arr.dtype) 
print("-"*20)

[1 2 3 4]
int32
--------------------
[1 2 3 4]
int64
--------------------


## Converting datatype of existing array

In [200]:
arr = np.array([1.1, 2.1, 3.1])
print('Original array : ',arr)
print(arr.dtype) 
print('-'*20)

newarr = arr.astype('i')

print('New array',newarr)
print(newarr.dtype) 
print('-'*20)

Original array :  [1.1 2.1 3.1]
float64
--------------------
New array [1 2 3]
int32
--------------------


In [201]:
arr = np.array([1.1, 2.1, 3.1])
print('Original array : ',arr)
print(arr.dtype) 
print('-'*20)

newarr = arr.astype(int)

print('New array',newarr)
print(newarr.dtype) 
print('-'*20)

Original array :  [1.1 2.1 3.1]
float64
--------------------
New array [1 2 3]
int64
--------------------


In [203]:
arr = np.array([1.1, 2.1, 0.0])
print('Original array : ',arr)
print(arr.dtype) 
print('-'*20)

newarr = arr.astype(bool)

print('New array',newarr)
print(newarr.dtype) 
print('-'*20)

Original array :  [1.1 2.1 0. ]
float64
--------------------
New array [ True  True False]
bool
--------------------


In [204]:
arr = np.array([1.1, 2.1, 0.0])
print('Original array : ',arr)
print(arr.dtype) 
print('-'*20)

newarr = arr.astype(str)

print('New array',newarr)
print(newarr.dtype) 
print('-'*20)

Original array :  [1.1 2.1 0. ]
float64
--------------------
New array ['1.1' '2.1' '0.0']
<U32
--------------------


## Copy vs View

In [212]:
print("changing the element at index 0 of the original array has no effect on copy")
print("-"*20)

arr = np.array([1, 2, 3, 4, 5])
print("arr before changing the element :",arr)
x = arr.copy()
arr[0] = 42

print("arr :",arr)
print("x   :",x) 

changing the element at index 0 of the original array has no effect on copy
--------------------
arr before changing the element : [1 2 3 4 5]
arr : [42  2  3  4  5]
x   : [1 2 3 4 5]


In [213]:
print("changing the element at index 0 of the original array has effect on view")
print("-"*20)

arr = np.array([1, 2, 3, 4, 5])
print("arr before changing the element :",arr)
x = arr.view()
arr[0] = 42

print("arr :",arr)
print("x   :",x) 

changing the element at index 0 of the original array has effect on view
--------------------
arr before changing the element : [1 2 3 4 5]
arr : [42  2  3  4  5]
x   : [42  2  3  4  5]


### Every NumPy array has the attribute `base` that returns None if the array owns the data.



In [218]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print("base for copy : ",x.base)
print("base for view : ",y.base , ", => returns the original array") 

base for copy :  None
base for view :  [1 2 3 4 5] , => returns the original array


## Shape

In [222]:
print("3 dimentional array, with 5 rows and 7 elements")
arr = np.random.randint(1,100, size=(3,5,7)) 
print(arr)
print("# of dims",arr.ndim)
print("Shape of the array is : ", arr.shape)
print("Size of the array is : ", arr.size)
print("-"*20)

3 dimentional array, with 5 rows and 7 elements
[[[19 97 83 44 30  2 25]
  [12 69  4 95 47 48 30]
  [ 5 98 42 50 15  7 63]
  [89 68 54 75 98 99 48]
  [62 92 96 21 67 12 57]]

 [[52 71 58 29  7 33 22]
  [87 98 73  3  5 44 62]
  [14  4 32 61 43 57 83]
  [ 4 54 36 40 55 17 49]
  [35 85 85 41  9 47 76]]

 [[93 94 47 58 74 54 39]
  [85 73 31 20 41 10 72]
  [80 84 82 81 94  8 58]
  [34  3 64  8 22  7 59]
  [92 28 57 30 19 87 31]]]
# of dims 3
Shape of the array is :  (3, 5, 7)
Size of the array is :  105
--------------------


## Reshape

In [240]:
print("3 dimentional array, with 4 rows and 2 elements")
arr = np.random.randint(1,100, size=(3,4,2)) 
print(arr)
print("# of dims",arr.ndim)
print("Shape of the array is : ", arr.shape)
print("Size of the array is : ", arr.size)
print("-"*20)

print("Reshaping array to 4 dimentional array, with 2 rows of 3, 2D arrays")
"""
4th dimension has 2 3D arrays
3rd dimesion has 3 2D arrays
2nd dimension has 2 arrays with 2 elements each
1st dimention has 2 elements 
"""
newarr = arr.reshape(2,3,2,2) # should be equal to dimension
print(newarr)
print("# of dims in newarr",newarr.ndim)
print("Shape of the newarr is : ", newarr.shape) # why this is not changing?
print("Size of the newarr is : ", newarr.size)
print("-"*20)

3 dimentional array, with 4 rows and 2 elements
[[[50 21]
  [72 80]
  [20 79]
  [12 45]]

 [[46 93]
  [77  8]
  [50 85]
  [68 46]]

 [[99  8]
  [88 42]
  [49 23]
  [ 6 92]]]
# of dims 3
Shape of the array is :  (3, 4, 2)
Size of the array is :  24
--------------------
Reshaping array to 4 dimentional array, with 2 rows of 3, 2D arrays
[[[[50 21]
   [72 80]]

  [[20 79]
   [12 45]]

  [[46 93]
   [77  8]]]


 [[[50 85]
   [68 46]]

  [[99  8]
   [88 42]]

  [[49 23]
   [ 6 92]]]]
# of dims in newarr 4
Shape of the newarr is :  (2, 3, 2, 2)
Size of the newarr is :  24
--------------------


In [241]:
# can reshape only to same size array

# Unknown dimension
# Note: We can not pass -1 to more than one dimension.

"""
4th dimension has 6 3D arrays
3rd dimesion has 2 2D arrays
2nd dimension has 2 arrays with 1 elements each
1st dimention has 1 elements 
"""
newarr = arr.reshape(-1,2,2,1) # should be equal to dimension, 4 in this case as we want 4D array
print(newarr)
print("# of dims in newarr",newarr.ndim)
print("Shape of the newarr is : ", newarr.shape)
print("Size of the newarr is : ", newarr.size)
print("-"*20)


[[[[50]
   [21]]

  [[72]
   [80]]]


 [[[20]
   [79]]

  [[12]
   [45]]]


 [[[46]
   [93]]

  [[77]
   [ 8]]]


 [[[50]
   [85]]

  [[68]
   [46]]]


 [[[99]
   [ 8]]

  [[88]
   [42]]]


 [[[49]
   [23]]

  [[ 6]
   [92]]]]
# of dims in newarr 4
Shape of the newarr is :  (6, 2, 2, 1)
Size of the newarr is :  24
--------------------


## Flattening the arrays

In [242]:
flatarr = newarr.reshape(-1)
print(flatarr)
print("# of dims in flatarr",flatarr.ndim)
print("Shape of the flatarr is : ", flatarr.shape)
print("Size of the flatarr is : ", flatarr.size)
print("-"*20)


[50 21 72 80 20 79 12 45 46 93 77  8 50 85 68 46 99  8 88 42 49 23  6 92]
# of dims in flatarr 1
Shape of the flatarr is :  (24,)
Size of the flatarr is :  24
--------------------


**Note:** There are a lot of functions for changing the shapes of arrays in numpy `flatten`, `ravel` and also for rearranging the elements `rot90`, `flip`, `fliplr`, `flipud` etc. These fall under Intermediate to Advanced section of numpy.

In [248]:
print("flatten", newarr.flatten())
print("ravel  ", newarr.ravel())

flatten [50 21 72 80 20 79 12 45 46 93 77  8 50 85 68 46 99  8 88 42 49 23  6 92]
ravel   [50 21 72 80 20 79 12 45 46 93 77  8 50 85 68 46 99  8 88 42 49 23  6 92]


## Iterating

In [250]:
# 1D array
arr = np.random.randint(1,100,10)
for i in arr:
    print(i)

28
84
61
91
85
82
32
41
44
60


In [254]:
# 2D array
arr = np.random.randint(1,100, size=(3,5))
for k,v in enumerate(arr):
    print("row-"+str(k)+" : ",v)

row-0 :  [18 82  8 70 34]
row-1 :  [92 50 92 98 29]
row-2 :  [77  2 17 24 44]


In [259]:
# 3D array
arr = np.random.randint(1,100, size=(3,5,2))
for i,x in enumerate(arr):
    print("row-"+str(i)+" : \n",x)
    print("-"*20)
    for j,y in enumerate(x):
        print("row-"+str(i)+","+str(j)+" : ",y)
    print("="*20)

row-0 : 
 [[19 42]
 [73 21]
 [97 85]
 [ 5 35]
 [ 6 31]]
--------------------
row-0,0 :  [19 42]
row-0,1 :  [73 21]
row-0,2 :  [97 85]
row-0,3 :  [ 5 35]
row-0,4 :  [ 6 31]
row-1 : 
 [[20 99]
 [ 2 79]
 [91 81]
 [90 92]
 [22 44]]
--------------------
row-1,0 :  [20 99]
row-1,1 :  [ 2 79]
row-1,2 :  [91 81]
row-1,3 :  [90 92]
row-1,4 :  [22 44]
row-2 : 
 [[82 52]
 [53 18]
 [12 30]
 [86 97]
 [ 8 11]]
--------------------
row-2,0 :  [82 52]
row-2,1 :  [53 18]
row-2,2 :  [12 30]
row-2,3 :  [86 97]
row-2,4 :  [ 8 11]


In [275]:
# 4D array
arr = np.random.randint(1,100, size=(2,1,3,4))
for i,x in enumerate(arr):
    print("4D row-"+str(i)+" : \n",x)
    print("-"*20)
    for j,y in enumerate(x):
        print("3D row-"+str(i)+","+str(j)+" : \n",y)
        for k,z in enumerate(y):
            print("2D row-"+str(i)+","+str(j)+","+str(k)+" : ",z)
            for l,a in enumerate(z):
                print("1D row-"+str(i)+","+str(j)+","+str(k)+","+str(l)+" : ",a)
            print("="*20)

4D row-0 : 
 [[[69 57 18 87]
  [85 86 50 43]
  [42 11 14  8]]]
--------------------
3D row-0,0 : 
 [[69 57 18 87]
 [85 86 50 43]
 [42 11 14  8]]
2D row-0,0,0 :  [69 57 18 87]
1D row-0,0,0,0 :  69
1D row-0,0,0,1 :  57
1D row-0,0,0,2 :  18
1D row-0,0,0,3 :  87
2D row-0,0,1 :  [85 86 50 43]
1D row-0,0,1,0 :  85
1D row-0,0,1,1 :  86
1D row-0,0,1,2 :  50
1D row-0,0,1,3 :  43
2D row-0,0,2 :  [42 11 14  8]
1D row-0,0,2,0 :  42
1D row-0,0,2,1 :  11
1D row-0,0,2,2 :  14
1D row-0,0,2,3 :  8
4D row-1 : 
 [[[64 85  2 23]
  [14 68 65 39]
  [ 2  7  4 33]]]
--------------------
3D row-1,0 : 
 [[64 85  2 23]
 [14 68 65 39]
 [ 2  7  4 33]]
2D row-1,0,0 :  [64 85  2 23]
1D row-1,0,0,0 :  64
1D row-1,0,0,1 :  85
1D row-1,0,0,2 :  2
1D row-1,0,0,3 :  23
2D row-1,0,1 :  [14 68 65 39]
1D row-1,0,1,0 :  14
1D row-1,0,1,1 :  68
1D row-1,0,1,2 :  65
1D row-1,0,1,3 :  39
2D row-1,0,2 :  [ 2  7  4 33]
1D row-1,0,2,0 :  2
1D row-1,0,2,1 :  7
1D row-1,0,2,2 :  4
1D row-1,0,2,3 :  33


## Iterating Arrays Using `nditer()`

The function nditer() is a helping function that can be used from very basic to very advanced iterations. 

In [278]:
# 3D array
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# prints each element in the nd array
for x in np.nditer(arr):
  print(x) 

1
2
3
4
5
6
7
8


## Iterating Array With Different Data Types

We can use `op_dtypes` argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in `nditer()` we pass `flags=['buffered']`.

In [284]:
# 3D array
arr = np.random.randint(1,100, size=(2,2,2))

for i in np.nditer(arr, op_dtypes=['S'], flags=['buffered']):
    print(i)

b'95'
b'81'
b'50'
b'98'
b'97'
b'27'
b'34'
b'70'


## nditer step size



In [303]:
# 3D array
arr = np.random.randint(1,100, size=(5,3,8))

print(arr)
print('-'*20)
print(arr[1:5:2, ::2,3::4])

"""
1. identify the rows from 3D array, 1:5:2 => every other row starting from 2nd element, (index 1 and 3)
2. get row at index 0 and 2 from array at index 1 and 3 from prev step
3. get every 4th element, starting form index 3 from prev step result
"""
for x in np.nditer(arr[1:5:2, ::2,3::4]):
  print(x) 


[[[19 99  4 24 42 89 27 34]
  [99 99 29 66 58 94 85 26]
  [52 36  9 58 16 90 87 13]]

 [[36  8 11 85 25  6 95 96]
  [58 92 36 81 87 12 39 43]
  [32 57 25 23 99 65 90 33]]

 [[69  4 72  6 80 34 17 79]
  [76 24 15 52 51 81 39 31]
  [69 76  6 16 59 16 54 32]]

 [[77 51 97 65 85 79 67 67]
  [93 66 82 32 74 30 68 20]
  [43 75 22 89 78 28 10 24]]

 [[39 91 77  7 11 28 26 16]
  [ 7 96  8 89 84 20 76 98]
  [13 81 51 45 82 37 20 23]]]
--------------------
[[[85 96]
  [23 33]]

 [[65 67]
  [89 24]]]
85
96
23
33
65
67
89
24


## Enumerated Iteration Using `ndenumerate()`

In [304]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr):
  print(idx, x) 

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [305]:
arr  = np.random.randint(1,100,size=(4,5,2))
for idx,x in np.ndenumerate(arr):
    print(idx,x)

(0, 0, 0) 92
(0, 0, 1) 56
(0, 1, 0) 88
(0, 1, 1) 1
(0, 2, 0) 42
(0, 2, 1) 71
(0, 3, 0) 79
(0, 3, 1) 18
(0, 4, 0) 84
(0, 4, 1) 31
(1, 0, 0) 71
(1, 0, 1) 20
(1, 1, 0) 13
(1, 1, 1) 43
(1, 2, 0) 21
(1, 2, 1) 13
(1, 3, 0) 51
(1, 3, 1) 17
(1, 4, 0) 15
(1, 4, 1) 11
(2, 0, 0) 4
(2, 0, 1) 98
(2, 1, 0) 78
(2, 1, 1) 57
(2, 2, 0) 1
(2, 2, 1) 13
(2, 3, 0) 60
(2, 3, 1) 95
(2, 4, 0) 54
(2, 4, 1) 67
(3, 0, 0) 95
(3, 0, 1) 44
(3, 1, 0) 69
(3, 1, 1) 88
(3, 2, 0) 58
(3, 2, 1) 30
(3, 3, 0) 97
(3, 3, 1) 13
(3, 4, 0) 95
(3, 4, 1) 79


## Joining NumPy Arrays

Joining means putting contents of two or more arrays in a single array.  
In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.  
axis = 0 => rows  
axis = 1 => cols  

    - concatinate
    - stack
        - hstack
        - vstack
        - dstack
    


In [306]:
# 1D concatination
arr1 = np.random.randint(1,100,size=(10))
arr2 = np.random.randint(1,100,size=(10))

arr = np.concatenate((arr1,arr2))

print(arr1)
print(arr2)
print(arr)

[11 29 25 27 32 60 20 36 78 41]
[99 80 40 89 99 23 88 72 21 23]
[11 29 25 27 32 60 20 36 78 41 99 80 40 89 99 23 88 72 21 23]


In [314]:
# 2D concatination
arr1 = np.random.randint(1,100,size=(3,10))
arr2 = np.random.randint(1,100,size=(3,1))# just 1 col but same number of rows
# arr2 = np.random.randint(1,100,size=(4,1))# just 1 col but different number of rows, this does not work in case of axis 1, will work for axis = 0

# with axis = 1
arr = np.concatenate((arr1,arr2), axis=1)

print(arr1)
print("-"*20)
print(arr2)
print("-"*20)
print(arr)

[[55 30 12 76 24 74 19 41 59 40]
 [ 4 50 56 39 31 84 14 28  8 55]
 [71 95  8 62 16 96 97 44 99 61]]
--------------------
[[19]
 [91]
 [69]]
--------------------
[[55 30 12 76 24 74 19 41 59 40 19]
 [ 4 50 56 39 31 84 14 28  8 55 91]
 [71 95  8 62 16 96 97 44 99 61 69]]


## Stack

In [320]:
arr1 = np.random.randint(1,50,size=(3,7))
arr2 = np.random.randint(1,50,size=(3,7))

arr = np.stack((arr1,arr2))
print(arr1)
print("-"*20)
print(arr2)
print("-"*20)
print("this puts arr1 on top of arr2 and creates 3D array as arr1 and arr2 are 2D arrays, has 2 rows")
print(arr)
print("# of dims",arr.ndim)
print("shape of dims",arr.shape)

[[47 10 37 38 13 33  2]
 [46 42 14 21 45 15  1]
 [20 14 13  8 22  7 25]]
--------------------
[[48 17 39 31 15  9 45]
 [31 47 24 26 15 14 46]
 [42  1 17 43 27 27 21]]
--------------------
this puts arr1 on top of arr2 and creates 3D array as arr1 and arr2 are 2D arrays, has 2 rows
[[[47 10 37 38 13 33  2]
  [46 42 14 21 45 15  1]
  [20 14 13  8 22  7 25]]

 [[48 17 39 31 15  9 45]
  [31 47 24 26 15 14 46]
  [42  1 17 43 27 27 21]]]
# of dims 3
shape of dims (2, 3, 7)


In [321]:
arr1 = np.random.randint(1,50,size=(3,7))
arr2 = np.random.randint(1,50,size=(3,7))

arr = np.stack((arr1,arr2), axis=1)
print(arr1)
print("-"*20)
print(arr2)
print("-"*20)
print("this puts row at index i from arr1 and arr2 on top of each other and creates 3D array as arr1 and arr2 are 2D arrays, has 3 rows now")
print(arr)
print("# of dims",arr.ndim)
print("shape of dims",arr.shape)

[[29  5 25 46 11 49 28]
 [26 23 12  8 29 27 22]
 [20 38 14 48  9 20 27]]
--------------------
[[27 13 26 35 13 44 13]
 [16 49 10  9 35 30 43]
 [ 2  2 10 22 46 12  7]]
--------------------
this puts row at index i from arr1 and arr2 on top of each other and creates 3D array as arr1 and arr2 are 2D arrays, has 3 rows now
[[[29  5 25 46 11 49 28]
  [27 13 26 35 13 44 13]]

 [[26 23 12  8 29 27 22]
  [16 49 10  9 35 30 43]]

 [[20 38 14 48  9 20 27]
  [ 2  2 10 22 46 12  7]]]
# of dims 3
shape of dims (3, 2, 7)


In [322]:
# hstack
arr1 = np.random.randint(1,50,size=(3,7))
arr2 = np.random.randint(1,50,size=(3,7))

arr = np.hstack((arr1,arr2))
print(arr1)
print("-"*20)
print(arr2)
print("-"*20)
print("concatinates corresponding row from arr1 and arr2 at index i, changes number of columns ")
print(arr)
print("# of dims",arr.ndim)
print("shape of dims",arr.shape)

[[30 31 19 16 24 22 14]
 [15  4 15 17 34 23 12]
 [ 8 26 29  5 44  6 28]]
--------------------
[[ 7 42 22 30 47 34 49]
 [28 17  3 14 25 31 27]
 [27  6 20 42  3 47 15]]
--------------------
this puts row at index i from arr1 and arr2 on top of each other and creates 3D array as arr1 and arr2 are 2D arrays, has 3 rows now
[[30 31 19 16 24 22 14  7 42 22 30 47 34 49]
 [15  4 15 17 34 23 12 28 17  3 14 25 31 27]
 [ 8 26 29  5 44  6 28 27  6 20 42  3 47 15]]
# of dims 2
shape of dims (3, 14)


In [323]:
# vstack
arr1 = np.random.randint(1,50,size=(3,7))
arr2 = np.random.randint(1,50,size=(3,7))

arr = np.vstack((arr1,arr2))
print(arr1)
print("-"*20)
print(arr2)
print("-"*20)
print("stacks one array on top of another array, changes number of rows")
print(arr)
print("# of dims",arr.ndim)
print("shape of dims",arr.shape)

[[13 21 33 39 17  6 27]
 [43 12 28  3 19  7 49]
 [44 11 11 11  7 35 17]]
--------------------
[[41 46 38 40 22 14 24]
 [ 7 36 21 17 26 10 26]
 [41  6 24 41  2 22 13]]
--------------------
similar to stack with axis 1
[[13 21 33 39 17  6 27]
 [43 12 28  3 19  7 49]
 [44 11 11 11  7 35 17]
 [41 46 38 40 22 14 24]
 [ 7 36 21 17 26 10 26]
 [41  6 24 41  2 22 13]]
# of dims 2
shape of dims (6, 7)


In [328]:
# dstack
arr1 = np.random.randint(1,50,size=(2,7))
arr2 = np.random.randint(1,50,size=(2,7))
arr3 = np.random.randint(1,50,size=(2,7))

arr = np.dstack((arr1,arr2,arr3))
print(arr1)
print("-"*20)
print(arr2)
print("-"*20)
print("creates rows in 3D array = # of rows in arr1,arr2,arr3, 2 in this case")
print("creates colums = # of arrays, arr1,arr2,arr3 = 3")
print("creates rows in each 2D array = # of cols in arr1,arr2,arr3 = 7")
print(arr)
print("# of dims",arr.ndim)
print("shape of dims",arr.shape)


[[ 7 46 11  5 27 31 21]
 [48 41 44 15  9 11 37]]
--------------------
[[34 36 22 26  7 13 28]
 [38 26 31  9 16 10 32]]
--------------------
creates rows in 3D array = # of rows in arr1,arr2,arr3, 2 in this case
creates colums = # of arrays, arr1,arr2,arr3 = 3
creates rows in each 2D array = # of cols in arr1,arr2,arr3 = 7
[[[ 7 34 25]
  [46 36 48]
  [11 22 47]
  [ 5 26  3]
  [27  7 33]
  [31 13  7]
  [21 28 31]]

 [[48 38 11]
  [41 26 35]
  [44 31 32]
  [15  9 32]
  [ 9 16 26]
  [11 10 11]
  [37 32  4]]]
# of dims 3
shape of dims (2, 7, 3)


## Splitting NumPy Arrays

Splitting is reverse of joining

we use `array_split` method as `split` method does not adjust if the number of elemets dont match


In [331]:
# split array into 3 arrays
arr = np.random.randint(1,50,size=(10))
newarr = np.array_split(arr, 3)
print(arr)
print("-"*20)
print()
print(newarr) 

[17  8 28 24 14 39 40 47 16 44]
--------------------
[array([17,  8, 28, 24]), array([14, 39, 40]), array([47, 16, 44])]


In [332]:
# split array into 4 arrays
arr = np.random.randint(1,50,size=(6))
newarr = np.array_split(arr, 4)
print(arr)
print("-"*20)
print(newarr) 

[24 25 36 25 27 40]
--------------------
[array([24, 25]), array([36, 25]), array([27]), array([40])]


In [339]:
# 2D array, split array into 3 arrays, col axis, so rows are adjusted
arr = np.random.randint(1,50,size=(5,3))
newarr = np.array_split(arr, 3)
print(arr)
print("-"*20)

# array will be 2D, number of columns will not change number of rows will be adjuted if required
for k,val in np.ndenumerate(newarr):
    print(k,"\n",val)

[[40 48 19]
 [ 7 11 29]
 [36 33 35]
 [ 3 29  8]
 [47 31 48]]
--------------------
(0,) 
 [[40 48 19]
 [ 7 11 29]]
(1,) 
 [[36 33 35]
 [ 3 29  8]]
(2,) 
 [[47 31 48]]


In [346]:
# 2D array, split array into 2 arrays, row axis, so cols are adjusted
arr = np.random.randint(1,50,size=(4,3))
newarr = np.array_split(arr, 2, axis=1)
print(arr)
print("-"*20)
print(newarr)
print("-"*20)
# array will be 2D, number of rows will not change number of cols will be adjuted if required
# first roe has 2 cols
# second row has 1 col

[[29 21 34]
 [26 13  9]
 [ 8 27  8]
 [26  1 15]]
--------------------
[array([[29, 21],
       [26, 13],
       [ 8, 27],
       [26,  1]]), array([[34],
       [ 9],
       [ 8],
       [15]])]
--------------------


In [353]:
# hsplit

arr = np.random.randint(1,50,size=(2,8))
newarr = np.hsplit(arr, 4)
print(arr)
print("-"*20)
print(newarr)
print("-"*20)
# need 4 arrays
# first 2 cols for each row make the first array
# 3rd and 4th cols for each row make the 2nd array
# 5th and 6th cols for each row make the 3rd array
# 7th and 8th cols for each row make the 4th array

[[35 11 25 37 48 48 22  5]
 [ 7 42 15 40 36 17 48 24]]
--------------------
[array([[35, 11],
       [ 7, 42]]), array([[25, 37],
       [15, 40]]), array([[48, 48],
       [36, 17]]), array([[22,  5],
       [48, 24]])]
--------------------


**`Note:`** Similar alternates to `vstack()` and `dstack()` are available as `vsplit()` and `dsplit()`.

## NumPy Searching Arrays

Searching array returns the indices of the result  
To search an array, use the `where()` method.

In [354]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x) 

(array([3, 5, 6]),)


In [358]:
# every third element till 50
arr = np.arange(1,50,3)
print(arr)

# index for every even number in the above list
x = np.where(arr%2 == 0)
print(x)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]
(array([ 1,  3,  5,  7,  9, 11, 13, 15]),)


In [359]:
# every fifth element till 50
arr = np.arange(1,50,5)
print(arr)

# index for every odd number in the above list
x = np.where(arr%2 == 1)
print(x)

[ 1  6 11 16 21 26 31 36 41 46]
(array([0, 2, 4, 6, 8]),)


### search sorted

In [375]:
arr = np.arange(2,50,2)
print(arr)
# search single value in sorted order
x = np.searchsorted(arr,14)
print(x)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
6


In [399]:
arr = np.arange(2,50,2)
print(arr)
# search single value in sorted order from right side
x = np.searchsorted(arr, 14, side='right') # this one has issue
print('Index of 14 is : ',x)
print("Element at "+str(x)+" is : ",arr[x])

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
Index of 14 is :  7
Element at 7 is :  16


In [384]:
arr = np.arange(2,50,2)
print(arr)
# search single value in sorted order from right side
x = np.searchsorted(arr, [14,48,40])
print(x)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
[ 6 23 19]


## Sorting Arrays

putting elements in ordered sequence

In [406]:
# number
arr = np.array([3, 2, 0, 1])
print(arr,"\n", np.sort(arr),'\n----\n') 

# String
arr = np.array(['banana', 'cherry', 'apple'])
print(arr, "\n", np.sort(arr),"\n----\n") 

# boolean
arr = np.array([True, False, True])
print(arr, "\n", np.sort(arr),"\n----\n") 

# 2D array
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(arr, "\n----\n", np.sort(arr)) 

[3 2 0 1] 
 [0 1 2 3] 
----

['banana' 'cherry' 'apple'] 
 ['apple' 'banana' 'cherry'] 
----

[ True False  True] 
 [False  True  True] 
----

[[3 2 4]
 [5 0 1]] 
----
 [[2 3 4]
 [0 1 5]]


In [409]:
# reversed sort
arr = np.array([3, 2, 45, 0, 1])
print(arr, "\n----\n", np.sort(arr)[::-1]) 
print('-'*20)
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(arr, "\n----\n", np.sort(arr)[:,::-1]) 

[ 3  2 45  0  1] 
----
 [45  3  2  1  0]
--------------------
[[3 2 4]
 [5 0 1]] 
----
 [[4 3 2]
 [5 1 0]]


## Filter arrays

Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.



A boolean index list is a list of booleans corresponding to indexes in the array.

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [410]:
arr = np.array([41, 42, 43, 44])
# print item at index 0 and 2 
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [413]:
# print elements higher than 42
arr = np.array([41, 42, 43, 44])

# create empty filter array
filter_arr = []

for i in arr:
    if i >42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

# pass the filter_array to actual array
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)



[False, False, True, True]
[43 44]


In [430]:
# Create a filter array that will return only even elements from the original array

arr = np.arange(1,21)

# create empty filter array
filter_arr = []

for i in arr:
    if i %2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

# pass the filter_array to actual array
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10 12 14 16 18 20]


# Creating Filter Directly From Array

In [431]:
# Create a filter array that will return only values higher than 42:
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr) 

[False False  True  True]
[43 44]


In [432]:
# Create a filter array that will return only even elements from the original array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filtered_arr = arr %2 ==0
newarr = arr[filtered_arr]
print(filter_arr)
print(newarr) 

[False False  True  True]
[2 4 6]
